[package]
name = "rust-arduino-sampler"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.13.5"
midir = "0.7.0"
hashbrown = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"